### PR TITLE
BANNO.NEWSUBCREATE.V1.CONFIG indexing fix

### PR DESCRIPTION
**Pull request by tkainz**
Modifying the method being used to index the share group from using the HTML  form index value to a manually assigned index value thus allowing the user to reorder the display of the share groups valid share types.

### CODE REVIEW

**Review by jordan-keenan — APPROVED** [review]
Changes look good Tom!

**Review by jordan-keenan — APPROVED** [review]
Code comment change Looks Good.

However; I think the following line, 1520, also needs t be changed to 30

       CHARACTERSEARCH(TEMPCHAR,".")-1))
[* TEK 03/16/23]
        CURRGROUP=TEMPNUM

**Comment by tkainz** [comment]
@jordan-keenan Thanks - date corrected and pushed to PR

**Review by jucarson — APPROVED** [review]
Looks Good

**Pull request merged**
