### PR TITLE
Update BANNO.NEWSUBCREATE.V1.POW

### PR DESCRIPTION
**Pull request by jucarson**
Broke up GETMINIMUMDEPOSIT into 2 procedures (PRINTMINFUNDAMT). Called calulation earlier in specfile for use in logic.

### CODE REVIEW

**Comment by tkainz** [comment]
Looks good JC - thanks

**Review by tkainz — APPROVED** [review]
Good to Go

**Review by jordan-keenan — COMMENTED** [review]
Looks good!  I see the last line was removed after the Include;
did you verify you still have a carriage return after the last include?

**Review by jordan-keenan — APPROVED** [review]
Code looks good! The next person who changes the code can just add the carriage return back to the end of the code.

**Pull request merged**
